### ISSUE TITLE
Can't resize the video player

### ISSUE THREAD

**Issue by jakesullyneytiri** [getgrav/grav-plugin-youtube#11]
Hi,
for some reason video is huge and i need to resize it but cannot find out how to :/ could you please add compatibility to resize or put yourown size to video so it isnt extremly big by default?

I also noticed it has add editor button but when i enable that editor still do not have a youtube button??

/Thanks

**Comment by flaviocopes** [comment]
The video will expand to the page width, which depends from theme to theme, and where you put the video markdown.

You can still resize it via CSS by targeting the `.grav-youtube` class.

The editor button works in Grav 1.1, is that what you're using, or Grav 1.0.10?

**Comment by jakesullyneytiri** [comment]
ty and i'm using stable version since i don't wanna risk any issues with RC or beta version that they got so yeah 1.0.10 is one i guess.

**Comment by ottod** [comment]
Sorry to hijack but I'm trying to stay on topic. I'm using the plugin (thanks to all contributors by the way) and I want to show only one video on my Grav website which happens to be 4:3. I know how to resize the player window manually but not with this plugin. Above there is mention of an edit button. Where is it? Could I use it to solve my problem? I'm using Grav 1.1.3, Admin 1.1.4 and Youtube 2.0.2. The editor button came enabled by default but I cannot find any difference in behavior when on or off.

**Comment by rhukster** [comment]
The editor button is on the Page editor in the toolbar (next to bold, italic, etc).
