### ISSUE TITLE
max-height not working

### ISSUE THREAD

**Issue by oneoftwo** [getgrav/grav-plugin-youtube#13]
Hi, in the current implementation, max-width correctly constrains the width of the video (or rather, the div around it), but max-height gets ignored -- increasing viewport height after reaching max-width will add black bars on the top and the bottom. This seems to be an issue with how CSS is interpreted. As per a couple of sources, the solution is to add another div to wrap the entire thing to constrain width before scaling height with the inner div:

```
<div class="grav-youtube-wrap">
  <div class="grav-youtube">
    <iframe></iframe>
  </div>
</div>
```

with CSS along the lines of (I personally prefer 1280px max width)

```
.grav-youtube {
    height: 0;
    padding-top: 25px;
    padding-bottom: 53.50%;
    margin-bottom: 10px;
    position: relative;
    overflow: hidden;
}

.grav-youtube-wrap {
    width: 1280px;
    max-width: 100%;
}
```

**Comment by rhukster** [comment]
This is the standard way to ensure the video is responsive: https://github.com/getgrav/grav-plugin-youtube/issues/22#issuecomment-332911178
