### ISSUE TITLE
The frameborder attribute on the iframe element is obsolete

### ISSUE THREAD

**Issue by WhiteWolfSix** [getgrav/grav-plugin-youtube#17]
As the title says, the frameborder attribute on the iframe element is obsolete.
![frameborder](https://cloud.githubusercontent.com/assets/24316177/21578241/d8c36e7e-cf78-11e6-9a10-e231e06d7a6d.jpg)

**Comment by flaviocopes** [comment]
This is still the code recommended by YouTube

![screen shot 2016-12-31 at 17 32 01](https://cloud.githubusercontent.com/assets/11783388/21578406/eb13f606-cf7e-11e6-8f25-51836585d733.png)

While not supported in the HTML5 specification, it's still supported by the browsers and there's no guarantee that the current page doctype is HTML5.
