### ISSUE TITLE
Play/pause on scroll

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-youtube#18]
Hello,
Can you tell me if it is possible to autoplay the video only on scroll over? Meaning that when the visitor comes scroll over the div where the player is embeded the video starts when he scrolls out of this region the video pauses. 

If you could just tell me the script and where to add it?

Your help would be very appreciated :)

**Comment by rhukster** [comment]
This is just using the standard youtube iframe.  It doesn't have advanced options like that.  There may be other more powerful 'video' plugins, but that is not the purpose of this one.
