### ISSUE TITLE
Only HTML video tags render

### ISSUE THREAD

**Issue by bgambier** [getgrav/grav-plugin-youtube#19]
I just installed the plugin to try it, but when I put a video in a page there is no video render, only HTML tags.

![image](https://cloud.githubusercontent.com/assets/11303103/22151793/f4c67038-df1f-11e6-8286-0f4c28b91eab.png)

The website runs on Grav v1.1.14, and I didn't change the default plugin configuration.

Is there anything else to do, or is it an incompatibility with the new grav version ?

Thx !

**Comment by Wojtziech** [comment]
It happens when pages/markdown/escape_markup is enabled in system configuration.

**Comment by rhukster** [comment]
That's the answer.
