### ISSUE TITLE
Shortcode doesn't work

### ISSUE THREAD

**Issue by traumturbulenzen** [getgrav/grav-plugin-youtube#33]
The shortcode renders a standard link with Link-Text "plugin:youtube". I use it with a grav item including a markdown field. 

On standard pages it works. Why it isn't recognizing in a simple markdownfield?

![Screenshot from 2020-04-07 10-48-17](https://user-images.githubusercontent.com/18284142/78649162-5ea14200-78bd-11ea-9f3b-d880a600c24b.png)

**Comment by dimitrilongo** [comment]
hi

i think same here https://github.com/getgrav/grav-plugin-youtube/issues/12

**Comment by mahagr** [comment]
Yes, closing the issue as needing `|markdown` in twig.
