### ISSUE TITLE
A options of plugin are ignored in shortcode

### ISSUE THREAD

**Issue by 01Kuzma** [getgrav/grav-plugin-youtube#37]
I don't know on which side is a bug: Plugin or Gantry, but they are related to each other.
Firstly I've placed a description on [Gantry 5 git](A options of plugin placed as Short Code in Custom HTML are ignored)

Placing a plugin into Gantry 5 Custom HTML particle ignored some options.

The `Short Code processing` is turned on (two checkboxes).
So, the youtube frame is loaded but it's ignoring plugin's options. As for example it ignores `lazy load`, `Modest branding`...
While plugin perfectly works placed in a markdown page

Also tested on fresh install of Grav 1.7.3, Gantry 5.4.36 and Helium 5.4.36.

**Comment by 01Kuzma** [comment]
The same is reproduced on a one-page website without `Gantry 5`

**Comment by 01Kuzma** [comment]
Some additional information is palced in this [Git ticket](https://github.com/gantry/gantry5/issues/2749)

**Comment by mahagr** [comment]
I checked the plugin and it seems to be an issue when generating shortcode and not related to Gantry.

**Comment by 01Kuzma** [comment]
@mahagr any chance for a solution?

**Comment by angusmcb** [comment]
I have proposed a fix for this :-)

**Comment by 01Kuzma** [comment]
@angusmcb, thank you! 
I've tested it few times. From the first sight, it seems working OK.
@rhukster can you merge it?
