### ISSUE TITLE
New SC syntax not working

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-plugin-youtube#38]
I tried to add YT video on page content and finally figured, that [new syntax](https://github.com/getgrav/grav-plugin-youtube#shortcode-syntax) doesn't work. In page I have:
```
[youtube]https://www.youtube.com/watch?v={ID}[/youtube]

[plugin:youtube](https://www.youtube.com/watch?v={ID})
```

Only second one is rendered. Same if only one video on page - only `[plugin:youtube]` is rendered

**Comment by rhukster** [comment]
Do you have shortcode-core installed? It's required for any shortcode to work.

I just tested the example in the README:

```
[youtube color=white autoplay=1]https://www.youtube.com/watch?v=BK8guP9ov2U[/youtube]
```

and it renders fine:

<img width="1264" alt="CleanShot 2021-02-16 at 12 22 50@2x" src="https://user-images.githubusercontent.com/1084697/108111271-b538ea00-7051-11eb-9f8d-f0a0ca54d032.png">

**Comment by rhukster** [comment]
Pretty sure this is it.  As the shortcode-core plugin is not a dependency because it's not required for regular syntax.  I've updated the readme with a NOTE about this.

**Comment by Karmalakas** [comment]
Ah, yes it works with shortcode core. Thanks for updating the Readme :)
