### ISSUE TITLE
Allow embed paramters to be configurable

### ISSUE THREAD

**Issue by hctom** [getgrav/grav-plugin-youtube#4]
The supported YouTube embed parameters should be configurable via the plugin configuration. See [here](https://developers.google.com/youtube/player_parameters?hl=de) (section: Parameters) for more details about all available parameters.

The following parameters should be configurable:

* ~~autohide~~ (This parameter has ben deprecated for HTML5 players)
* autoplay
* cc_load_policy
* color
* controls
* disablekb
* enablejsapi
* fs
* hl
* iv_load_policy
* loop
* modestbranding
* origin
* playsinline
* rel
* showinfo
* ~~theme~~ (This parameter has ben deprecated for HTML5 players)

In addition to this, it should also be possible to enable Privacy-enhanced mode for YouTube videos (YouTube won’t store information about visitors unless they play a video).

All other parameters may be added via template overrides manually when #3 is implemented.

I will give this a try and provide a new pull request with all the changes

**Comment by hctom** [comment]
Please see the filed pull request #6 to get this enhancement in.

**Comment by rhukster** [comment]
Great thanks!
