### ISSUE TITLE
Black Borders on Video Caused by Extra 20px Padding

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-plugin-youtube#40]
Hello,

An update on an old issue #22 

This is still an issue - there are still black bars on the top and bottom of a standard 16:9 aspect ratio video.

This can be solved by removing the fixed 20px padding-top. #34 

Maybe this used to be a standard method (perhaps because it was to accommodate youtube controls?), but it is definitely not needed with the way the youtube player works now.

See for example here:
https://flaviocopes.com/responsive-youtube-videos/

**Comment by rhukster** [comment]
merged and released.
