### ISSUE TITLE
Error after update to 2.0.0

### ISSUE THREAD

**Issue by Balindil** [getgrav/grav-plugin-youtube#7]
After update the page is down with error:
E_COMPILE_ERROR - Grav\Plugin\YoutubePlugin::onTwigExtensions(): Failed opening required 'xxxxx/user/plugins/youtube/classes/twig/YoutubeTwigExtension.php' (include_path='.:/package/host/localhost/php-5.6.12/lib/php')

After downgrade to 1.1.0 everything is fine again.

**Comment by rhukster** [comment]
Was a case sensitivity issue so that's why it never showed up on my mac.  Fixed and released in version 2.0.1 which should show up in GPM in about an hour.
