### ISSUE TITLE
`youtu.be` link is not working

### ISSUE THREAD

**Issue by h6ah4i** [getgrav/grav-plugin-youtube#9]
Hi. I noticed that this plugin cannot handle a short URL (`https://youtu.be/{video_id}`) properly.

Also, I found a bug in the definition of the youtube URL regex string. In the current regex, protocol part is only affects to non shortened domain.

---

##### Current implementation:
```php
const YOUTUBE_REGEX = '(?:https?:\/{2}www.youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})';
```

##### Proposed fix:
```php
const YOUTUBE_REGEX = '(?:https?:\/{2}(?:(?:www.youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=))|(?:youtu\.be\/)))([a-zA-Z0-9_-]{11})'
```

---

Thanks.

**Comment by flaviocopes** [comment]
Go ahead and post a PR, I'll merge it

**Comment by h6ah4i** [comment]
@FrugalGeek Hi. Thanks for your quick response. I have just made a PR :)

**Comment by flaviocopes** [comment]
Thanks, confirmed and tested, merged!

**Comment by h6ah4i** [comment]
😄
